home_care_tips = [
  {:week=>1,
  :label=>"Protect your plants",
  :time_of_year=>"January",
  :description=>
   "Cold fronts are often below freezing, but also bring high speed winds. Be sure to cover up your sensitive plants (bedroom sheets work wonders). Bring potted plants inside the garage to keep them from freezing. when temperatures drop.",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>10,
  :label=>"Don't forget to change those clocks!",
  :time_of_year=>"March 7",
  :description=>"With DST fast approaching, it's time to manually change all the clocks in your home. Don't forget appliances such as your microwave as well as timers for lighting around the home too.",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>12,
  :label=>"Touch up your entryway",
  :time_of_year=>"Spring",
  :description=>"Chances are, your entryway sees a lot of traffic and could use a touch up. A fresh coat of paint can make a big difference! Let us know if we can help.",
  :show_button=>true,
  :service_provider=>"painter",
  :other_provider=>nil,
  :default_hn_chat_message=>"I'd like to touch up my painting. Can you help? "},
 {:week=>13,
  :label=>"Change your fridge filter",
  :time_of_year=>"Spring",
  :description=>
   "Make sure you're regularly changing your fridge water filter! After changing it, be sure to run 4 gallons of water through the dispenser to flush any debris that may have built up in the old filter!",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>14,
  :label=>"Turn on your irrigation",
  :time_of_year=>"Spring",
  :description=>
   "It's that time of year! Time for the flowers to bloom. Run a self test on your irrigation and make sure all the heads function. Notice any issues? Let us know so we can get your system back up and running!",
  :show_button=>true,
  :service_provider=>"other",
  :other_provider=>"Irrigation",
  :default_hn_chat_message=>"I noticed an issue with my irrigation."},
 {:week=>15,
  :label=>"Powerwash your driveway",
  :time_of_year=>"Spring",
  :description=>
   "Over time, driveways and sidewalks may become stained from dirt, rain and driving. Rent a power washer to clean it up and pay special attention to the areas where downspouts are as there tends to be more debris in those areas. Or let us schedule a pro! ",
  :show_button=>true,
  :service_provider=>"other",
  :other_provider=>"Powerwash",
  :default_hn_chat_message=>"I'd like to have pressure washing performed."},
 {:week=>16,
  :label=>"Remove hose bib covers",
  :time_of_year=>"Spring",
  :description=>"It's time to remove those hose bib covers so you can get to watering the plants and lawns again!",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>17,
  :label=>"Inspect your external A/C unit",
  :time_of_year=>"Spring",
  :description=>
   "With temperatures rising, it's a good opportunity to check your condensers (outdoor A/C unit). Check the insulation is in good condition around the copper tubes and that the unit is not clogged with debris. Also, listen to the unit when it's running. If anything sounds out of the ordinary, we'd be happy to schedule a check up!",
  :show_button=>false,
  :service_provider=>"HVAC",
  :other_provider=>nil,
  :default_hn_chat_message=>"I'd like to have my A/C checked."},
 {:week=>25,
  :label=>"Take care of your pool",
  :time_of_year=>"Summer",
  :description=>
   "Be sure to skim your pool daily and check the filter to keep debris from lingering and breaking down in the water. Does your pool need more care? Let us schedule a more thorough service call.",
  :show_button=>true,
  :service_provider=>"other",
  :other_provider=>"Pool maintenance",
  :default_hn_chat_message=>"My pool needs maintenance work."},
 {:week=>26,
  :label=>"Take care of those plants",
  :time_of_year=>"Summer",
  :description=>"It's getting hot out there! Your irrigation does a lot, but for these hot days, you might want to double-check that your more sensitive plants are getting enough water.",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>27,
  :label=>"Check door weather sealing",
  :time_of_year=>"Summer",
  :description=>
   "Check your exterior doors, do you see light coming in or feel any air? You may need new weather stripping. If that isn't the solution, you may need to have the door adjusted to get the proper seal. Let us know if you need help.",
  :show_button=>true,
  :service_provider=>"handyman",
  :other_provider=>"Carpenter",
  :default_hn_chat_message=>"My doors aren't keeping out cold air. Can someone come and look at them?"},
 {:week=>39,
  :label=>"Change your fridge filter",
  :time_of_year=>"Fall",
  :description=>
   "Make sure you're regularly changing your fridge water filter! After changing it, be sure to run 4 gallons of water through the dispenser to flush any debris that may have built up in the old filter!",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>40,
  :label=>"Shut down your irrigation",
  :time_of_year=>"Fall",
  :description=>"As the temps cool, our lawns go dormant. Time to shutdown your irrigation. Depending on your system, you may need to relieve pressure in the lines. Need help? Let us know! ",
  :show_button=>true,
  :service_provider=>"other",
  :other_provider=>"irrigation",
  :default_hn_chat_message=>"I'd like to have someone winterize my irrigation."},
 {:week=>41,
  :label=>"Install hose bib covers",
  :time_of_year=>"Fall",
  :description=>"You won't be needing your outdoor hoses, so it's good practice to disconnect your hoses and place a bib cover on them to protect from freezing temps this winter.",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>48,
  :label=>"Check your windows",
  :time_of_year=>"Winter",
  :description=>"Have you noticed a draft coming from your windows? It might be increasing your energy bill by 20%! Let us know if you need your windows checked ASAP.",
  :show_button=>true,
  :service_provider=>"other",
  :other_provider=>"Window repair",
  :default_hn_chat_message=>"I need to have my window seals checked."},
 {:week=>49,
  :label=>"Be prepared this winter",
  :time_of_year=>"December",
  :description=>
   "Always be prepared for a winter power outage. Check that you have plenty of bottled water and shelf-stable food in case you lose power for any extended period of time. Have a first aid kit, battery powered radio and portable battery packs for your phones.",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>50,
  :label=>"Check door weather sealing",
  :time_of_year=>"Winter",
  :description=>
   "Check your exterior doors, do you see light coming in or feel any air? You may need new weather stripping. If that isn't the solution, you may need to have the door adjusted to get the proper seal. Let us know if you need help.",
  :show_button=>true,
  :service_provider=>"handyman",
  :other_provider=>"Carpenter",
  :default_hn_chat_message=>"My doors aren't keeping out cold air. Can someone come and look at them?"},
 {:week=>51,
  :label=>"Store your firewood",
  :time_of_year=>"Winter",
  :description=>
   "If you plan on using your fireplace, be sure to store your wood outside and keep it covered to prevent the elements from ruining it. It's not recommended to keep wood in your home for any extended period of time as it may attract insects.",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>52,
  :label=>"Check your fireplace",
  :time_of_year=>"Winter",
  :description=>
   "If you have a gas fireplace, regularly check the ignition and flame holds. If your fireplace burns wood, it's recommended to have a professional do a proper chimney cleaning annually (we can book it for you).",
  :show_button=>true,
  :service_provider=>"other",
  :other_provider=>"Chimney sweep",
  :default_hn_chat_message=>"I need to book a chimney cleaning"},
 {:week=>-1,
  :label=>"Keep your gutters clean",
  :time_of_year=>"Any",
  :description=>
   "Cleaning your gutters regularly can save you money on replacement gutters, and even on repairing roof damage! Clogged gutters can overflow and break, and put strain on the roof itself. In the winter, they can fill with ice that causes thawing damage or strains the material. Need help? Let us know!",
  :show_button=>true,
  :service_provider=>"gutter cleaner",
  :other_provider=>nil,
  :default_hn_chat_message=>"My gutters need to be cleaned. Can you help? "},
 {:week=>-1,
  :label=>"Check for leaks",
  :time_of_year=>"Any",
  :description=>"Check under sinks and around toilets for signs of water. Found any leaks? We can help! ",
  :show_button=>true,
  :service_provider=>"plumber",
  :other_provider=>nil,
  :default_hn_chat_message=>"I noticed a leak issue. Can you help?"},
 {:week=>-1,
  :label=>"Check your appliances",
  :time_of_year=>"Any",
  :description=>
   "It's great to do a regular check on your appliances. Verify that all of your burners turn on, all of your lights operate, and everything functions correctly. Notice any issues? Let us know!",
  :show_button=>true,
  :service_provider=>"appliance tech",
  :other_provider=>nil,
  :default_hn_chat_message=>"I am having an appliance issue. Can you help me? "},
 {:week=>-1,
  :label=>"Inspect your washer",
  :time_of_year=>"Any",
  :description=>
   "To make sure your washer doesn't have any leaks, check that the the supply lines are tight and that the drain hose is secured to prevent it from falling out. These simple corrections can prevent big problems down the line!",
  :show_button=>true,
  :service_provider=>"appliance tech",
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>-1,
  :label=>"Toilet Inspections",
  :time_of_year=>"Any",
  :description=>
   "Toilets can be a cause of unintentional water usage. Open the tank and check that the water level is not above the overflow tube. Is the flapper forming a good seal? If you notice any issues, let us have a plumber check them out.",
  :show_button=>true,
  :service_provider=>"plumber",
  :other_provider=>nil,
  :default_hn_chat_message=>"I noticed an issue with my toilet. Can you help? "},
 {:week=>-1,
  :label=>"Inspect your dryer",
  :time_of_year=>"Any",
  :description=>
   "Pull out the lint catch and use a dryer brush to break up any lint that is stuck. Check your flex duct behind the dryer to ensure it isn't kinked. These are the most common reasons for a dryer to not dry well. You maybe able to solve that issue in 5 minutes! Want someone to do it for you? Let us know!",
  :show_button=>true,
  :service_provider=>"appliance tech",
  :other_provider=>nil,
  :default_hn_chat_message=>"I'd like to get my dryer vent cleaned. Can you help?"},
 {:week=>-1,
  :label=>"Test outlets in your home",
  :time_of_year=>"Any",
  :description=>
   "Using a voltage tester purchased from your local hardware store, you can verify your outlets have power (and are wired correctly). You can also test your GFCIs with it. Have an issue with an outlet? Let us know so we can get an electrician to take care of that for you!",
  :show_button=>true,
  :service_provider=>"electrician",
  :other_provider=>nil,
  :default_hn_chat_message=>"I'd like to have an electrician look at my outlets. "},
 {:week=>-1,
  :label=>"Inspect your water heater",
  :time_of_year=>"Any",
  :description=>
   "Water heaters can have leaks that are tricky to identify. Be sure to check the pan under the heater for any signs of water. Also look at the rest of the unit: notice any rust or corrosion? Let us get a plumber out to further evaluate the condition.",
  :show_button=>true,
  :service_provider=>"plumber",
  :other_provider=>nil,
  :default_hn_chat_message=>"I noticed an issue with my water heater. Can you help? "},
 {:week=>-1,
  :label=>"Check your faucets",
  :time_of_year=>"Any",
  :description=>
   "It helps to give your faucets a regular check up. Verify they turn freely, the hot/cold handles move with ease, and the sprayers freely move about and function correctly. Have an issue or time for an upgrade? Let us handle that!",
  :show_button=>true,
  :service_provider=>"plumber",
  :other_provider=>nil,
  :default_hn_chat_message=>"I have a faucet issue I'd like to address. "},
 {:week=>-1,
  :label=>"Check cabinets and drawers",
  :time_of_year=>"Any",
  :description=>
   "Open and close all of your cabinet doors and drawers. Are they all moving smoothly? If not, it may be time for new sliders. Or perhaps a slow close hinge upgrade to prevent slamming. Let us know.",
  :show_button=>true,
  :service_provider=>"handyman",
  :other_provider=>nil,
  :default_hn_chat_message=>"I have an issue with my cabinets/drawers. Can you assist? "},
 {:week=>-1,
  :label=>"Clean your kitchen faucet aerators",
  :time_of_year=>"Any",
  :description=>
   "The aerators to your kitchen faucet and bathroom faucets can get clogged with debris from hard water (restricting flow). Be sure to remove the aerators  and clean off any debris. A simple wrench or \"key\" for your specific faucet will allow you to do this (or we can help)",
  :show_button=>true,
  :service_provider=>"plumber",
  :other_provider=>nil,
  :default_hn_chat_message=>"I'd like to have my faucet aerators cleaned. Can you help? "},
 {:week=>-1,
  :label=>"Clean excess dryer lint",
  :time_of_year=>"Any",
  :description=>
   "While you might be cleaning lint from your dryer every cycle, some still gets through. Vacuum the inside of the dryer every month to catch any additional build up. It's also recommended to get the entire dryer vent cleaned once a year to improve efficiency and promote safety. Let us know if you want us to handle it!",
  :show_button=>true,
  :service_provider=>"Dryer vent cleaning",
  :other_provider=>nil,
  :default_hn_chat_message=>"Can you arrange for my dryer vent to be cleaned? "},
 {:week=>-1,
  :label=>"Check your window screens",
  :time_of_year=>"Any",
  :description=>
   "Check the screens on your windows and screen doors. Torn screens aren't only unsightly, but allow pests into your home. If a screen is loose, it often just needs to be placed back under the plastic cord. A simple flathead screwdriver will take care of that. Don't want to DIY? Let us handle it!",
  :show_button=>true,
  :service_provider=>"handyman",
  :other_provider=>nil,
  :default_hn_chat_message=>"I'd like to have a handyman help fix my window screens. "},
 {:week=>-1,
  :label=>"Check the salt in your softener",
  :time_of_year=>"Any",
  :description=>
   "When is the last time you checked the salt level in your water softener? Most units have digital indicators to let you know the level. Be sure to open it and verify the level is accurate and refill if needed. Or let us know if you'd like this addressed as part of your maintenance work.",
  :show_button=>true,
  :service_provider=>"handyman",
  :other_provider=>nil,
  :default_hn_chat_message=>"My water softener needs salt added. Can you arrange this? "},
 {:week=>-1,
  :label=>"Test your smoke detectors",
  :time_of_year=>"Any",
  :description=>
   "Perform a smoke detector test. For a linked system, you can press and hold the test button and all the detectors should alert (make sure your house is empty first!). Wear hearing protection and be safe using a ladder to reach them. Running into problems? Let us help you out!",
  :show_button=>true,
  :service_provider=>"handyman",
  :other_provider=>nil,
  :default_hn_chat_message=>"I need to have my smoke detectors checked"},
 {:week=>-1,
  :label=>"Check your window blinds",
  :time_of_year=>"Any",
  :description=>"It's good to regularly check that your blinds open/close and hoist up and down properly. If you notice any issues, we'd be happy to arrange someone to take a look.",
  :show_button=>true,
  :service_provider=>"handyman",
  :other_provider=>"Blind specialist ",
  :default_hn_chat_message=>"I noticed an issue with my blinds. Can someone come and check it out?"},
 {:week=>-1,
  :label=>"Resetting your breaker",
  :time_of_year=>"Any",
  :description=>
   "Have an outlet that has tripped and lost power? Sometimes, resetting the breaker is as simple as finding the switch in the off position on your electrical panel and resetting it to on. Does the same circuit keep tripping? It's worth having an electrician investigate. ",
  :show_button=>true,
  :service_provider=>"electrician",
  :other_provider=>nil,
  :default_hn_chat_message=>"I have an issue with an electrical circuit tripping. Can you help? "},
 {:week=>-1,
  :label=>"Check your fire extinguisher",
  :time_of_year=>"Any",
  :description=>"A working fire extinguisher is essential for every home. Check yours regularly: make sure the tamper seal is intact and the nozzle is free from corrosion and obstructions.",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>-1,
  :label=>"Are your doors squeaking?",
  :time_of_year=>"Any",
  :description=>"Notice any squeaking when you open and close the doors around your home? A quick spray of silicone based oil (e.g WD40) will eliminate this right away! ",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>-1,
  :label=>"Check and clean your air returns",
  :time_of_year=>"Any",
  :description=>
   "Your air return pulls air into your HVAC system and often is very visible in your home. Using a brush or damp cloth, clean off any dust or dirt stuck to the grilles. This will not only be aesthetically pleasing, but also allow for better airflow for your A/C.",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>-1,
  :label=>"Test your security system",
  :time_of_year=>"Any",
  :description=>"It's recommended to test your security system once a month. Hopefully you never need to rely on your system, but if something unfortunate occurs, it's reassuring to know it will work.",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>-1,
  :label=>"Keep your garbage disposal fresh",
  :time_of_year=>"Any",
  :description=>"It's important to keep your disposal clean to prevent unwanted odors. Adding a little baking soda and vinegar and running hot water regularly can really help!",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>-1,
  :label=>"Kitchen Pantry Organization",
  :time_of_year=>"Any",
  :description=>
   "Our kitchen pantries can get a little disorganized. Every six months, do a quick check for any items that are expired and stock up on non-perishables. This will help you make sure you always have food on-hand in an emergency, while also helping you keep your pantry more organized.",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil},
 {:week=>-1,
  :label=>"Clean your exhaust fan filter",
  :time_of_year=>"Any",
  :description=>
   "When is the last time you cleaned your exhaust fan filter? This can be done easily by filling your sink (or a bucket) with hot water, 1/4 cup of baking soda and a squirt of detergent. Let the filter soak for about 10 minutes, scrub with non-abrasive brush, rinse and dry with paper towels, and re-secure. Very easy!",
  :show_button=>false,
  :service_provider=>nil,
  :other_provider=>nil,
  :default_hn_chat_message=>nil}
]

HomeCareTip.transaction do
  puts "Home Care Tips: #{HomeCareTip.count}"
  HomeCareTip.destroy_all
  puts "Home Care Tips: #{HomeCareTip.count}"
  HomeCareTip.insert_all(home_care_tips)
  puts "Home Care Tips: #{HomeCareTip.count}"
end
