# Ensure our dependencies are kept up-to-date
# See https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates

version: 2
updates:

  # check updates for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Ruby
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "mileszim"
    reviewers:
      - "mileszim"