environment:
  - NAMESPACE_ORG=houseninja
  - NAMESPACE_ENV
  - NAMESPACE_SERVICE
  - NAMESPACE_RESOURCE
resources:
  database:
    type: postgres
    options:
      version: 14
      storage: 20
  redis:
    type: redis
    options:
      version: 6.2
services:
  web:
    # annotations:
    #   - test.annotation.org/value=foobar
    # build: .
    command: bundle exec rails server
    domain: ${DOMAIN}
    environment:
      - NAMESPACE_SERVICE=api
      - NAMESPACE_RESOURCE=app
      - RACK_ENV
      - RAILS_ENV
      - RAILS_MASTER_KEY
    health: /health
    image: ghcr.io/houseninjadojo/api
    internal: false
    port: 3000
    resources:
      - database
      - redis
    termination:
      grace: 45
    timeout: 120
    deployment:
      minimum: 50
      maximum: 200
  worker:
    command: bundle exec sidekiq -q critical -q default -q mailers
    environment:
      - NAMESPACE_SERVICE=api
      - NAMESPACE_RESOURCE=app
      - RACK_ENV
      - RAILS_ENV
      - RAILS_MASTER_KEY
    image: ghcr.io/houseninjadojo/api
    internal: true
    resources:
      - database
      - redis
    termination:
      grace: 45
    deployment:
      minimum: 50
      maximum: 200
  # metrics:
  #   agent: true
  #   image: awesome/metrics