version: '3.1'

services:
  database:
    image: postgres:14
    # restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:6
    # restart: always
    ports:
      - 6379:6379
