# fly.toml file generated for hn-api-sandbox on 2023-02-22T18:15:36-08:00

app = "hn-api-sandbox"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "registry.fly.io/hn-api-sandbox:latest"
  # dockerfile = "Dockerfile"

[env]
  # ADMINIUM_URL = ""
  APPNAME = "api"
  # DATABASE_URL = ""
  DD_AGENT_MAJOR_VERSION = "7"   
  DD_AGENT_VERSION = "7.40.1-1"
  # DD_API_KEY = ""
  DD_APM_ENABLED = true
  DD_DISABLE_HOST_METRICS = true 
  DD_DYNO_HOST = true
  DD_ENV = "sandbox"
  DD_LOG_LEVEL = "error"
  DD_PROCESS_AGENT = true
  DD_PROCESS_AGENT_ENABLED = true
  DD_TRACE_DEBUG = false
  # DISABLE_DATADOG_AGENT = true
  LANG = "en_US.UTF-8" 
  NAMESPACE_ENV = "sandbox"
  NAMESPACE_ORG = "houseninja"
  NAMESPACE_SERVICE = "api"
  RACK_ENV = "sandbox"
  RAILS_ENV = "sandbox"   
  RAILS_LOG_TO_STDOUT = "enabled"
  # RAILS_MASTER_KEY = ""
  RAILS_SERVE_STATIC_FILES = "enabled"
  # REDIS_URL = ""
  # SECRET_KEY_BASE=""
  STRIPE_WEBHOOK_DISABLED = true
  STUNNEL_ENABLED = true
  # TREBLLE_API_KEY = ""
  # TREBLLE_PROJECT_ID=""

[experimental]
  auto_rollback = true

[processes]
  web = "bin/rails server"
  worker = "bin/sidekiq -C config/sidekiq.yml"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
