domains: &domains
  app: app.houseninja.co
  api: api.houseninja.co             # default domain
  documents: documents.houseninja.co
  landing: www.houseninja.co         # default www domain
  localhost: localhost

shared:
  name: api                          # name of the app
  lang: en_US.UTF-8
  port: 3000
  email:
    name: 'House Ninja'
    default: House Ninja <hello@houseninja.co>   # default email
    reply_to: hello@houseninja.co    # reply to email
  protocol: 'https'
  app_store_url: 'https://apps.apple.com/us/app/house-ninja/id1603710358'

development:
  domains:
    <<: *domains
    api: localhost:3000
    app: localhost:4200
    assets: localhost:3000
    documents: localhost:3000
  protocol: 'http'

test:
  domains:
    <<: *domains
    api: localhost:3000
    app: localhost:4200
    assets: localhost:3000
    documents: localhost:3000

sandbox:
  domains:
    <<: *domains
    api: sandbox.api.houseninja.co    # staging app domain
    app: payment-approval.houseninja.pages.dev
    documents: sandbox.documents.houseninja.co

production:
  domains:
    <<: *domains
    api: api.houseninja.co            # production app domain
    app: app.houseninja.co
    documents: documents.houseninja.co
