class Coupon < ActiveHash::Base
  self.data = [
    {
      id: "VeNkKlf7",
      coupon_id: "VeNkKlf7",
      name: "(INTERNAL) Free Forever",
      percent_off: "100",
      amount_off: nil,
      duration: "forever",
      duration_in_months: nil,
      livemode: true,
      system_coupon: true,
      active: true,
    },
    {
      id: "referral_code",
      coupon_id: "referral_code",
      name: "Referral Codes",
      percent_off: "100",
      amount_off: nil,
      duration: "repeating",
      duration_in_months: 2,
      livemode: true,
      system_coupon: true,
      active: true,
    },
    {
      id: "Uz8oOt9R",
      coupon_id: "Uz8oOt9R",
      name: "Six Months Free",
      percent_off: "100",
      amount_off: nil,
      duration: "repeating",
      duration_in_months: 6,
      livemode: true,
      system_coupon: false,
      active: true,
    },
    {
      id: "rkz9aE52",
      coupon_id: "rkz9aE52",
      name: "Four Months Free",
      percent_off: "100",
      amount_off: nil,
      duration: "repeating",
      duration_in_months: 4,
      livemode: true,
      system_coupon: false,
      active: true,
    },
    {
      id: "oGyAM0v1",
      coupon_id: "oGyAM0v1",
      name: "Three Months Free",
      percent_off: "100",
      amount_off: nil,
      duration: "repeating",
      duration_in_months: 3,
      livemode: true,
      system_coupon: false,
      active: true,
    },
    {
      id: "fpQGtS10",
      coupon_id: "fpQGtS10",
      name: "Two Months Free",
      percent_off: "100",
      amount_off: nil,
      duration: "repeating",
      duration_in_months: 2,
      livemode: true,
      system_coupon: false,
      active: true,
    },
    {
      id: "VNKMqTav",
      coupon_id: "VNKMqTav",
      name: "One Month Free",
      percent_off: "100",
      amount_off: nil,
      duration: "repeating",
      duration_in_months: 1,
      livemode: true,
      system_coupon: false,
      active: true,
    },
  ]
end
