name: ci / build

# Trigger after tests pass
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "ci / tests"
    branches:
      - main
    types: 
      - completed
  push:
    branches:
      - docker

concurrency:
  group: build-release

env:
  RUBY_VERSION: 3.1.2
  BUILD_MODE: true
  DOCKER_REPO: ghcr.io/houseninjadojo/api

jobs:
  release:
    name: release container
    uses: houseninjadojo/api/.github/workflows/reusable.build.yml@main
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    with:
      docker_repo: ghcr.io/houseninjadojo/api
      dockerfile: Dockerfile
    secrets:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_MASTER_KEY }}
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CI_CD }}