name: ci / build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Gemfile.lock
      - platform/docker/Dockerfile.builder
      - platform/docker/Dockerfile.intermediate

jobs:
  base:
    name: base container
    uses: houseninjadojo/api/.github/workflows/reusable.build.yml@main
    with:
      docker_repo: ghcr.io/houseninjadojo/api-base
      dockerfile: platform/docker/Dockerfile.builder
    secrets:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_MASTER_KEY }}
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CI_CD }}
  intermediate:
    name: intermediate container
    uses: houseninjadojo/api/.github/workflows/reusable.build.yml@main
    with:
      docker_repo: ghcr.io/houseninjadojo/api-intermediate
      dockerfile: platform/docker/Dockerfile.intermediate
    secrets:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_MASTER_KEY }}
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CI_CD }}