name: CI / Build / Release Container

on:
  push:
    branches:
      - fly

# Trigger after tests pass
# on:
  # workflow_run:
    # workflows:
    #   - "CI / Tests"
    # branches:
      # - main
    # types: 
    #   - completed

concurrency:
  group: build-release

env:
  RUBY_VERSION: 3.1.2
  BUILD_MODE: true
  DOCKER_REPO: ghcr.io/houseninjadojo/api

jobs:
  release:
    name: Release Container
    uses: houseninjadojo/api/.github/workflows/reusable.build.yml@fly
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    with:
      docker_repo: ghcr.io/houseninjadojo/api
      dockerfile: Dockerfile
    secrets:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_MASTER_KEY }}
      GHCR_TOKEN: ${{ secrets.GHCR_PAT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CI_CD }}