name: ci / linters

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  RUBY_VERSION: 3.2.1
  RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_MASTER_KEY }}
  # ImageOS: ubuntu20 # Self Hosted

jobs:
  rubocop:
    name: "rubocop"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --parallel
