name: build container

on:
  workflow_call:
    inputs:
      docker_repo:
        required: true
        type: string
      build_args:
        required: false
        type: string
      dockerfile:
        required: false
        type: string
        default: Dockerfile
    secrets:
      RAILS_MASTER_KEY:
        required: true
      GHCR_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

env:
  RUBY_VERSION: 3.2.1
  BUILD_MODE: true
  DOCKER_REPO: ${{ inputs.docker_repo }}
  # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # -
      #   uses: act10ns/slack@v1
      #   with:
      #     status: starting
      #     channel: '#ci-cd'
      #     message: Starting Docker Build and Push...
      #   if: always()
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # Future Miles: Don't replace this with GITHUB_TOKEN
          # We need to use GHCR_PAT in order to trigger the package update event
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
            ${{ inputs.build_args }}
          tags: ${{ env.DOCKER_REPO }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      # -
      #   uses: act10ns/slack@v1
      #   with:
      #     status: ${{ job.status }}
      #     steps: ${{ toJson(steps) }}
      #     channel: '#ci-cd'
      #   if: always()